server:
  port: 9001

spring:
  application:
    name: master-data-service
  config:
    import: configserver:http://localhost:9999
  zipkin:
    base-url: http://localhost:9411
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true